# This file is Copyright 2024 Volatility Foundation and licensed under the
# Volatility Software License 1.0 which is available at
# https://www.volatilityfoundation.org/license/vsl-v1.0
#
"""Resolve kernel-module C struct layouts from BTF (BPF Type Format) blobs
found directly in a memory image.

Since ~5.x, most distro kernels build with CONFIG_DEBUG_INFO_BTF_MODULES=y:
every loaded kernel module carries an exact ".BTF" section (generated by
pahole from that specific compiled build) describing its own struct
layouts, mapped into kernel memory once the module loads. That means any
memory image from such a system already contains exact struct layouts for
module-only structs (xt_table, nft_table, ...) -- no network access and no
approximation from a version-tagged source tree, unlike xtables_layout.py's
opt-in GitHub fetch, which stays as a fallback for kernels without BTF.

Format reference: https://docs.kernel.org/bpf/btf.html

SPLIT BTF STRING RESOLUTION (not documented in the kernel docs above):
per-module BTF is "split" against the base (vmlinux) BTF so modules don't
repeat the kernel's own type/string tables. A split blob's own
btf_header.str_len covers only its OWN new strings, but name_off values
are not purely local -- they index into a conceptual space where the base
blob's strings occupy [0, base_str_len) and the split blob's own strings
follow right after. A name_off >= base_str_len resolves to
split_strings[name_off - base_str_len]; below that it refers to the base
blob's string table, which this module never parses. That's not a
practical limitation for structs defined by the module itself (the
common case for callers of this module), since those always land in the
local range. The base blob is identified as simply the largest valid BTF
blob found (vmlinux's string table dwarfs any single module's).

This module resolves only what the xtables plugins need: member NAMES and
BIT offsets within a struct/union, plus the struct's own byte size. It
does not resolve individual member type sizes (that needs cross-references
into the base blob's type table) -- callers needing a field's size use the
delta to the next field's offset instead (struct_to_offset_size_map),
sidestepping that entirely.
"""

from __future__ import annotations

import logging
import struct
from typing import Iterator, NamedTuple, Sequence

from volatility3.framework.layers import scanners

vollog = logging.getLogger(__name__)

BTF_MAGIC = b"\x9f\xeb"  # 0xeB9F, little-endian

_HEADER_FORMAT = (
    "<HBBIIIII"  # magic, version, flags, hdr_len, type_off, type_len, str_off, str_len
)
_HEADER_SIZE = struct.calcsize(_HEADER_FORMAT)

BTF_KIND_INT = 1
BTF_KIND_PTR = 2
BTF_KIND_ARRAY = 3
BTF_KIND_STRUCT = 4
BTF_KIND_UNION = 5
BTF_KIND_ENUM = 6
BTF_KIND_FWD = 7
BTF_KIND_TYPEDEF = 8
BTF_KIND_VOLATILE = 9
BTF_KIND_CONST = 10
BTF_KIND_RESTRICT = 11
BTF_KIND_FUNC = 12
BTF_KIND_FUNC_PROTO = 13
BTF_KIND_VAR = 14
BTF_KIND_DATASEC = 15
BTF_KIND_FLOAT = 16
BTF_KIND_DECL_TAG = 17
BTF_KIND_TYPE_TAG = 18
BTF_KIND_ENUM64 = 19

_STRUCT_LIKE_KINDS = (BTF_KIND_STRUCT, BTF_KIND_UNION)

# Sanity bound on total blob size (matches the bound used by the BPFVol3
# project's btf_extract plugin, which pioneered scanning memory for BTF).
_MAX_BLOB_SIZE = 1 << 29


class BtfMember(NamedTuple):
    name: str
    bit_offset: (
        int  # always a plain bit offset -- our target structs have no real C bitfields
    )


class BtfStruct(NamedTuple):
    name: str
    byte_size: int
    members: list[BtfMember]


class BtfHeaderInfo(NamedTuple):
    hdr_len: int
    type_off: int
    type_len: int
    str_off: int
    str_len: int


class BtfCandidate(NamedTuple):
    """A physical-memory offset whose header structurally validated as BTF,
    with the full blob bytes already read in. Not yet known to be a base
    (vmlinux) or split (module) blob -- see resolve_struct_layouts().
    """

    phys_offset: int
    header: BtfHeaderInfo
    data: bytes


def _parse_header(data: bytes) -> BtfHeaderInfo | None:
    if len(data) < _HEADER_SIZE:
        return None
    magic, _version, flags, hdr_len, type_off, type_len, str_off, str_len = (
        struct.unpack_from(_HEADER_FORMAT, data, 0)
    )
    if magic != 0xEB9F or flags != 0 or hdr_len != _HEADER_SIZE:
        return None
    if type_off != 0 or type_len == 0 or str_len == 0:
        return None
    if type_off >= str_off or type_off + type_len > str_off:
        return None
    total = hdr_len + str_off + str_len
    if total <= 0 or total > _MAX_BLOB_SIZE:
        return None
    return BtfHeaderInfo(
        hdr_len=hdr_len,
        type_off=type_off,
        type_len=type_len,
        str_off=str_off,
        str_len=str_len,
    )


def _kind_extra_len(kind: int, vlen: int) -> int:
    """Number of bytes of kind-specific data following the 12-byte btf_type
    common header, for kinds we don't parse in detail -- needed to keep the
    type-section cursor correctly positioned regardless of which kinds
    appear in the stream.
    """
    if kind == BTF_KIND_INT:
        return 4
    if kind == BTF_KIND_ARRAY:
        return 12  # btf_array{type,index_type,nelems}
    if kind in _STRUCT_LIKE_KINDS:
        return vlen * 12  # btf_member{name_off,type,offset} each
    if kind == BTF_KIND_ENUM:
        return vlen * 8  # btf_enum{name_off,val}
    if kind == BTF_KIND_ENUM64:
        return vlen * 12  # btf_enum64{name_off,val_lo32,val_hi32}
    if kind == BTF_KIND_FUNC_PROTO:
        return vlen * 8  # btf_param{name_off,type}
    if kind == BTF_KIND_VAR:
        return 4  # btf_var{linkage}
    if kind == BTF_KIND_DATASEC:
        return vlen * 12  # btf_var_secinfo{type,offset,size}
    if kind == BTF_KIND_DECL_TAG:
        return 4  # btf_decl_tag{component_idx}
    # FWD, TYPEDEF, VOLATILE, CONST, RESTRICT, FUNC, FLOAT, TYPE_TAG: no extra data
    return 0


def _walk_type_section_structurally(type_section: bytes) -> bool:
    """Cheap structural validity check: can the type section be walked to
    completion without an out-of-bounds read? Doesn't need the string table
    at all, so it's used to reject the many incidental 2-byte magic matches
    found when scanning multi-gigabyte physical memory, before we know
    which candidate is the base blob (needed for name resolution).
    """
    pos = 0
    try:
        while pos + 12 <= len(type_section):
            _name_off, info, _size_or_type = struct.unpack_from(
                "<III", type_section, pos
            )
            pos += 12
            kind = (info >> 24) & 0x1F
            vlen = info & 0xFFFFFF
            if kind > BTF_KIND_ENUM64:
                return False
            extra_len = _kind_extra_len(kind, vlen)
            if extra_len:
                if pos + extra_len > len(type_section):
                    return False
                pos += extra_len
        return pos == len(type_section)
    except (struct.error, IndexError):
        return False


def _parse_structs(
    data: bytes,
    header: BtfHeaderInfo,
    base_strings: bytes,
) -> dict[str, BtfStruct]:
    """Parse every named struct/union in a blob's type section.

    ``base_strings`` is the base (vmlinux) blob's own string-table bytes,
    or b"" when parsing the base blob itself. Pahole/LLVM deduplicate
    common field/type names (e.g. "size", "list", "name") into the base
    string table even for module-only structs, so a split blob's member
    names routinely need both tables: name_off < len(base_strings) resolves
    against the base blob's strings, name_off >= len(base_strings) against
    this blob's own local string table at (name_off - len(base_strings)).
    See the module docstring for the derivation.
    """
    local_strings = data[
        header.hdr_len + header.str_off : header.hdr_len
        + header.str_off
        + header.str_len
    ]
    base_len = len(base_strings)

    def name_at(off: int) -> str:
        if off < base_len:
            table, local_off = base_strings, off
        else:
            table, local_off = local_strings, off - base_len
        if local_off < 0 or local_off >= len(table):
            return ""
        end = table.find(b"\x00", local_off)
        if end < 0:
            return ""
        return table[local_off:end].decode("ascii", errors="replace")

    type_section = data[
        header.hdr_len + header.type_off : header.hdr_len
        + header.type_off
        + header.type_len
    ]
    structs_by_name: dict[str, BtfStruct] = {}
    pos = 0
    while pos + 12 <= len(type_section):
        name_off, info, size_or_type = struct.unpack_from("<III", type_section, pos)
        pos += 12
        kind = (info >> 24) & 0x1F
        vlen = info & 0xFFFFFF
        kind_flag = bool(info & 0x8000_0000)

        if kind in _STRUCT_LIKE_KINDS:
            members: list[BtfMember] = []
            for _ in range(vlen):
                m_name_off, _m_type, m_offset = struct.unpack_from(
                    "<III", type_section, pos
                )
                pos += 12
                bit_offset = m_offset & 0xFF_FFFF if kind_flag else m_offset
                mname = name_at(m_name_off)
                if mname:
                    members.append(BtfMember(name=mname, bit_offset=bit_offset))
            sname = name_at(name_off)
            if sname:
                structs_by_name[sname] = BtfStruct(
                    name=sname, byte_size=size_or_type, members=members
                )
            continue

        extra_len = _kind_extra_len(kind, vlen)
        pos += extra_len

    return structs_by_name


def _iter_candidate_offsets(layer, context) -> Iterator[int]:
    yield from layer.scan(context=context, scanner=scanners.BytesScanner(BTF_MAGIC))


def scan_for_btf_candidates(context, layer_name: str) -> list[BtfCandidate]:
    """Scan a layer's underlying physical memory for BTF blobs (the base
    kernel's vmlinux BTF plus any per-module split BTF).

    This is the expensive part (a full memory scan for a 2-byte magic), so
    callers should scan once per image and reuse the result -- see
    xtables_layout.py's caching of this call.
    """
    virt_layer = context.layers[layer_name]
    phys_name = virt_layer.config.get("memory_layer")
    phys_layer = context.layers[phys_name] if phys_name else virt_layer

    candidates: list[BtfCandidate] = []
    seen_starts = set()
    scanned = 0
    for offset in _iter_candidate_offsets(phys_layer, context):
        scanned += 1
        if offset in seen_starts:
            continue
        try:
            header_preview = phys_layer.read(offset, _HEADER_SIZE)
        except Exception:
            continue
        header = _parse_header(header_preview)
        if header is None:
            continue
        total = header.hdr_len + header.str_off + header.str_len
        try:
            blob_data = phys_layer.read(offset, total)
        except Exception:
            continue
        type_section = blob_data[
            header.hdr_len + header.type_off : header.hdr_len
            + header.type_off
            + header.type_len
        ]
        if not _walk_type_section_structurally(type_section):
            continue
        seen_starts.add(offset)
        candidates.append(
            BtfCandidate(phys_offset=offset, header=header, data=blob_data)
        )

    vollog.debug(
        "BTF scan of %s: %d magic-byte candidate(s), %d structurally valid BTF blob(s)",
        layer_name,
        scanned,
        len(candidates),
    )
    return candidates


def find_struct_layout(
    candidates: Sequence[BtfCandidate], struct_name: str
) -> BtfStruct | None:
    """Search every candidate BTF blob for a struct/union definition named
    ``struct_name``. The largest blob (by string-table size) is treated as
    the base (vmlinux) blob and parsed with no string-offset shift; every
    other blob is treated as split (per-module) BTF and parsed with the
    base's str_len as the name-resolution offset (see module docstring).
    """
    if not candidates:
        return None
    base = max(candidates, key=lambda c: c.header.str_len)
    base_strings = base.data[
        base.header.hdr_len + base.header.str_off : base.header.hdr_len
        + base.header.str_off
        + base.header.str_len
    ]
    for candidate in candidates:
        strings_for_base_lookup = b"" if candidate is base else base_strings
        structs = _parse_structs(
            candidate.data, candidate.header, strings_for_base_lookup
        )
        found = structs.get(struct_name)
        if found is not None:
            return found
    return None


def struct_to_offset_map(btf_struct: BtfStruct) -> dict[str, int]:
    """Convert a BtfStruct's members into {field_name: byte_offset}.

    Byte offset assumes byte-aligned (non-bitfield) members, true for every
    struct these plugins care about (xt_table, xt_table_info, ipt_entry-
    adjacent types, nft_table, nft_chain, nft_base_chain).
    """
    return {m.name: m.bit_offset // 8 for m in btf_struct.members}
