name: build-pypi

on:
  push:
    branches:
      - stable
      - develop
      - 'release/**'

  pull_request:
    branches:
      - stable
      - 'release/**'

jobs:

  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38  # v5.4.0
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build PyPi packages
      run: |
        python -m build

    - name: Archive dist
      uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1  # v4.6.1
      with:
        name: volatility3-pypi
        path: |
          dist/
