---
name: Ruff

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - uses: astral-sh/ruff-action@39f75e526a505e26a302f8796977b50c13720edf  # v3.2.1
        with:
          args: check
          src: "."
