name: Test Volatility3
on: [push, pull_request]
jobs:

  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38  # v5.4.0
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip Cmake build
        pip install .[test]

    - name: Build PyPi packages
      run: |
        python -m build

    - name: Download images
      run: |
        mkdir test_images
        cd test_images
        curl -sLO "https://downloads.volatilityfoundation.org/volatility3/images/linux-sample-1.bin.gz"
        gunzip linux-sample-1.bin.gz
        curl -sLO "https://downloads.volatilityfoundation.org/volatility3/images/win-xp-laptop-2005-06-25.img.gz"
        gunzip win-xp-laptop-2005-06-25.img.gz
        cd -

    - name: Download and Extract symbols
      run: |
        cd ./volatility3/symbols
        curl -sLO https://downloads.volatilityfoundation.org/volatility3/symbols/linux.zip
        unzip linux.zip
        cd -

    - name: Testing...
      run: |
        # VolShell
        pytest ./test/test_volatility.py --volatility=volshell.py --image-dir=./test_images -k test_windows_volshell -v
        pytest ./test/test_volatility.py --volatility=volshell.py --image-dir=./test_images -k test_linux_volshell -v

        # Volatility
        pytest ./test/test_volatility.py --volatility=vol.py --image-dir=./test_images -k "test_windows and not test_windows_volshell" -v
        pytest ./test/test_volatility.py --volatility=vol.py --image-dir=./test_images -k "test_linux and not test_linux_volshell" -v

    - name: Clean up post-test
      run: |
        rm -rf test_images
        cd volatility3/symbols
        rm -rf linux
        rm -rf linux.zip
        cd -
